version: "3"
services:
  signal-cli-grpc-api:
    image: dattito/signal-cli-grpc-api:latest
    environment:
      - USE_NATIVE=0
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * *
      - PORT=9090
    ports:
      - "9090:9090" #map docker port 9090 to host port 9090.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
